name: Build Docker images

on:
  pull_request:
    paths:
      - runtime/**

jobs:
  publish:
    name: Building images
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build images
        run: make docker-images
